/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace JobMarketplace {
  export type JobStruct = {
    client: AddressLike;
    evaluator: AddressLike;
    provider: AddressLike;
    description: string;
    budget: BigNumberish;
    expiresAt: BigNumberish;
    status: BigNumberish;
    deliverableRef: BytesLike;
  };

  export type JobStructOutput = [
    client: string,
    evaluator: string,
    provider: string,
    description: string,
    budget: bigint,
    expiresAt: bigint,
    status: bigint,
    deliverableRef: string
  ] & {
    client: string;
    evaluator: string;
    provider: string;
    description: string;
    budget: bigint;
    expiresAt: bigint;
    status: bigint;
    deliverableRef: string;
  };
}

export interface JobMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRefund"
      | "complete"
      | "createJob"
      | "fund"
      | "getJob"
      | "getJobCount"
      | "reject"
      | "setProvider"
      | "submit"
      | "token"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobCompleted"
      | "JobCreated"
      | "JobExpired"
      | "JobFunded"
      | "JobRejected"
      | "JobSubmitted"
      | "ProviderSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complete",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [string, BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reject",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProvider",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submit",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "complete", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
}

export namespace JobCompletedEvent {
  export type InputTuple = [jobId: BigNumberish, reason: BytesLike];
  export type OutputTuple = [jobId: bigint, reason: string];
  export interface OutputObject {
    jobId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    evaluator: AddressLike,
    provider: AddressLike,
    description: string,
    budget: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    evaluator: string,
    provider: string,
    description: string,
    budget: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    evaluator: string;
    provider: string;
    description: string;
    budget: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobExpiredEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFundedEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRejectedEvent {
  export type InputTuple = [jobId: BigNumberish, reason: BytesLike];
  export type OutputTuple = [jobId: bigint, reason: string];
  export interface OutputObject {
    jobId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, deliverableRef: BytesLike];
  export type OutputTuple = [jobId: bigint, deliverableRef: string];
  export interface OutputObject {
    jobId: bigint;
    deliverableRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderSetEvent {
  export type InputTuple = [jobId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [jobId: bigint, provider: string];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): JobMarketplace;
  waitForDeployment(): Promise<this>;

  interface: JobMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRefund: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  complete: TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;

  createJob: TypedContractMethod<
    [
      description: string,
      budget: BigNumberish,
      evaluator: AddressLike,
      provider: AddressLike,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  fund: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [JobMarketplace.JobStructOutput],
    "view"
  >;

  getJobCount: TypedContractMethod<[], [bigint], "view">;

  reject: TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;

  setProvider: TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike],
    [void],
    "nonpayable"
  >;

  submit: TypedContractMethod<
    [jobId: BigNumberish, deliverableRef: BytesLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "complete"
  ): TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      description: string,
      budget: BigNumberish,
      evaluator: AddressLike,
      provider: AddressLike,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [JobMarketplace.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reject"
  ): TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProvider"
  ): TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submit"
  ): TypedContractMethod<
    [jobId: BigNumberish, deliverableRef: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobExpired"
  ): TypedContractEvent<
    JobExpiredEvent.InputTuple,
    JobExpiredEvent.OutputTuple,
    JobExpiredEvent.OutputObject
  >;
  getEvent(
    key: "JobFunded"
  ): TypedContractEvent<
    JobFundedEvent.InputTuple,
    JobFundedEvent.OutputTuple,
    JobFundedEvent.OutputObject
  >;
  getEvent(
    key: "JobRejected"
  ): TypedContractEvent<
    JobRejectedEvent.InputTuple,
    JobRejectedEvent.OutputTuple,
    JobRejectedEvent.OutputObject
  >;
  getEvent(
    key: "JobSubmitted"
  ): TypedContractEvent<
    JobSubmittedEvent.InputTuple,
    JobSubmittedEvent.OutputTuple,
    JobSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderSet"
  ): TypedContractEvent<
    ProviderSetEvent.InputTuple,
    ProviderSetEvent.OutputTuple,
    ProviderSetEvent.OutputObject
  >;

  filters: {
    "JobCompleted(uint256,bytes32)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,address,string,uint256,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobExpired(uint256)": TypedContractEvent<
      JobExpiredEvent.InputTuple,
      JobExpiredEvent.OutputTuple,
      JobExpiredEvent.OutputObject
    >;
    JobExpired: TypedContractEvent<
      JobExpiredEvent.InputTuple,
      JobExpiredEvent.OutputTuple,
      JobExpiredEvent.OutputObject
    >;

    "JobFunded(uint256)": TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;
    JobFunded: TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;

    "JobRejected(uint256,bytes32)": TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;
    JobRejected: TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;

    "JobSubmitted(uint256,bytes32)": TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
    JobSubmitted: TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;

    "ProviderSet(uint256,address)": TypedContractEvent<
      ProviderSetEvent.InputTuple,
      ProviderSetEvent.OutputTuple,
      ProviderSetEvent.OutputObject
    >;
    ProviderSet: TypedContractEvent<
      ProviderSetEvent.InputTuple,
      ProviderSetEvent.OutputTuple,
      ProviderSetEvent.OutputObject
    >;
  };
}
